//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BHANSA_FrqMgmt.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCL_US_Checked {
            get {
                return ((bool)(this["CCL_US_Checked"]));
            }
            set {
                this["CCL_US_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCL_UN_Checked {
            get {
                return ((bool)(this["CCL_UN_Checked"]));
            }
            set {
                this["CCL_UN_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCL_UW_Checked {
            get {
                return ((bool)(this["CCL_UW_Checked"]));
            }
            set {
                this["CCL_UW_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCL_LS_Checked {
            get {
                return ((bool)(this["CCL_LS_Checked"]));
            }
            set {
                this["CCL_LS_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCL_LN_Checked {
            get {
                return ((bool)(this["CCL_LN_Checked"]));
            }
            set {
                this["CCL_LN_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CCL_US_Value {
            get {
                return ((string)(this["CCL_US_Value"]));
            }
            set {
                this["CCL_US_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CCL_UN_Value {
            get {
                return ((string)(this["CCL_UN_Value"]));
            }
            set {
                this["CCL_UN_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CCL_UW_Value {
            get {
                return ((string)(this["CCL_UW_Value"]));
            }
            set {
                this["CCL_UW_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CCL_LS_Value {
            get {
                return ((string)(this["CCL_LS_Value"]));
            }
            set {
                this["CCL_LS_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CCL_LN_Value {
            get {
                return ((string)(this["CCL_LN_Value"]));
            }
            set {
                this["CCL_LN_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Division_Level {
            get {
                return ((string)(this["Division_Level"]));
            }
            set {
                this["Division_Level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SMATSA_UW_Checked {
            get {
                return ((bool)(this["SMATSA_UW_Checked"]));
            }
            set {
                this["SMATSA_UW_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SMATSA_UN_Checked {
            get {
                return ((bool)(this["SMATSA_UN_Checked"]));
            }
            set {
                this["SMATSA_UN_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMATSA_UW_Value {
            get {
                return ((string)(this["SMATSA_UW_Value"]));
            }
            set {
                this["SMATSA_UW_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMATSA_UN_Value {
            get {
                return ((string)(this["SMATSA_UN_Value"]));
            }
            set {
                this["SMATSA_UN_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SMATSA_Lower_Value {
            get {
                return ((string)(this["SMATSA_Lower_Value"]));
            }
            set {
                this["SMATSA_Lower_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SMATSA_Lower_Checked {
            get {
                return ((bool)(this["SMATSA_Lower_Checked"]));
            }
            set {
                this["SMATSA_Lower_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120.700")]
        public string LDZA {
            get {
                return ((string)(this["LDZA"]));
            }
            set {
                this["LDZA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("123.600")]
        public string LDDU {
            get {
                return ((string)(this["LDDU"]));
            }
            set {
                this["LDDU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120.875")]
        public string LDSP {
            get {
                return ((string)(this["LDSP"]));
            }
            set {
                this["LDSP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118.800")]
        public string LDOS {
            get {
                return ((string)(this["LDOS"]));
            }
            set {
                this["LDOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135.050")]
        public string ZGFIC {
            get {
                return ((string)(this["ZGFIC"]));
            }
            set {
                this["ZGFIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("136.450")]
        public string LQSA {
            get {
                return ((string)(this["LQSA"]));
            }
            set {
                this["LQSA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120.225")]
        public string LQMO {
            get {
                return ((string)(this["LQMO"]));
            }
            set {
                this["LQMO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120.350")]
        public string LQTZ {
            get {
                return ((string)(this["LQTZ"]));
            }
            set {
                this["LQTZ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("118.950")]
        public string LQBK {
            get {
                return ((string)(this["LQBK"]));
            }
            set {
                this["LQBK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135.575")]
        public string FIC {
            get {
                return ((string)(this["FIC"]));
            }
            set {
                this["FIC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("119.100")]
        public string LYBE {
            get {
                return ((string)(this["LYBE"]));
            }
            set {
                this["LYBE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("135.150")]
        public string LYPG {
            get {
                return ((string)(this["LYPG"]));
            }
            set {
                this["LYPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[+382 20 414 005]")]
        public string Sector_LYPG {
            get {
                return ((string)(this["Sector_LYPG"]));
            }
            set {
                this["Sector_LYPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Free text")]
        public string Free_Text_1 {
            get {
                return ((string)(this["Free_Text_1"]));
            }
            set {
                this["Free_Text_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Free text")]
        public string Free_Text_2 {
            get {
                return ((string)(this["Free_Text_2"]));
            }
            set {
                this["Free_Text_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Free text")]
        public string Free_Text_3 {
            get {
                return ((string)(this["Free_Text_3"]));
            }
            set {
                this["Free_Text_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("325")]
        public string Chief_Sup_Ext {
            get {
                return ((string)(this["Chief_Sup_Ext"]));
            }
            set {
                this["Chief_Sup_Ext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CCL_LW_Checked {
            get {
                return ((bool)(this["CCL_LW_Checked"]));
            }
            set {
                this["CCL_LW_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CCL_LW_Value {
            get {
                return ((string)(this["CCL_LW_Value"]));
            }
            set {
                this["CCL_LW_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool I_am_Server {
            get {
                return ((bool)(this["I_am_Server"]));
            }
            set {
                this["I_am_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("N/A")]
        public string Position_Name {
            get {
                return ((string)(this["Position_Name"]));
            }
            set {
                this["Position_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Server_Interface_Index {
            get {
                return ((int)(this["Server_Interface_Index"]));
            }
            set {
                this["Server_Interface_Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238.1.1.1")]
        public string Server_Multicast_Address {
            get {
                return ((string)(this["Server_Multicast_Address"]));
            }
            set {
                this["Server_Multicast_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public string Server_Port {
            get {
                return ((string)(this["Server_Port"]));
            }
            set {
                this["Server_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238.1.1.1")]
        public string CWP1_Multicast_Address {
            get {
                return ((string)(this["CWP1_Multicast_Address"]));
            }
            set {
                this["CWP1_Multicast_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2001")]
        public string CWP1_Port {
            get {
                return ((string)(this["CWP1_Port"]));
            }
            set {
                this["CWP1_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238.1.1.1")]
        public string CWP2_Multicast_Address {
            get {
                return ((string)(this["CWP2_Multicast_Address"]));
            }
            set {
                this["CWP2_Multicast_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2002")]
        public string CWP2_Port {
            get {
                return ((string)(this["CWP2_Port"]));
            }
            set {
                this["CWP2_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238.1.1.1")]
        public string CWP3_Multicast_Address {
            get {
                return ((string)(this["CWP3_Multicast_Address"]));
            }
            set {
                this["CWP3_Multicast_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2003")]
        public string CWP3_Port {
            get {
                return ((string)(this["CWP3_Port"]));
            }
            set {
                this["CWP3_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Client_Interface_Index {
            get {
                return ((int)(this["Client_Interface_Index"]));
            }
            set {
                this["Client_Interface_Index"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238.1.1.1")]
        public string Client_Multicast_Address {
            get {
                return ((string)(this["Client_Multicast_Address"]));
            }
            set {
                this["Client_Multicast_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public string Client_Port {
            get {
                return ((string)(this["Client_Port"]));
            }
            set {
                this["Client_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("238.1.1.1")]
        public string Client_Brodacast_Address {
            get {
                return ((string)(this["Client_Brodacast_Address"]));
            }
            set {
                this["Client_Brodacast_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2001")]
        public string Client_Broadcast_Port {
            get {
                return ((string)(this["Client_Broadcast_Port"]));
            }
            set {
                this["Client_Broadcast_Port"] = value;
            }
        }
    }
}
